name: mylawyer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # STATE MANAGEMENT
  mobx: #^2.0.3
  flutter_mobx: #^2.0.1

  # Base
  nb_utils: #^4.4.4
  intl: #^0.17.0
  flutter_vector_icons: #^1.0.0
  google_fonts: #^2.1.0

  # Common
  share: #^2.0.4
  url_launcher: #^6.0.3
  http: #^0.13.3
  html: #^0.15.0
  package_info: #^2.0.2

  # IMAGES
  cached_network_image: #^3.1.0
  image_picker: #^0.8.1+3
  file_picker: #^3.0.1
  photo_view: #^0.12.0
  card_swiper: #^1.0.2

  # UI
  simple_animations: #^3.1.1
  flutter_svg: #^0.22.0
  flutter_staggered_grid_view: #^0.4.0
  flutter_staggered_animations: #^1.0.0

  # MAP
  google_maps_flutter: #^2.0.6
  geolocator: #^7.3.1
  geocoding: #^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: #^2.0.2
  build_runner: #^2.0.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
